#ifndef DFCC_VERSION_H
#define DFCC_VERSION_H

#define DFCC_NAME "dfcc"
#define DFCC_VERSION "0.0"

#define GETTEXT_PACKAGE DFCC_NAME

#define DFCC_LOOP_DETECTION_ENV "DFCC_SPAWNING_PROCESS"

#define DFCC_HOOKFS_FILENAME "hookfs.so"


#endif /* DFCC_VERSION_H */
